# Generated by Django 4.2.29 on 2026-03-29 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_details', models.TextField()),
                ('food_type', models.CharField(choices=[('cooked', 'Cooked Food'), ('raw', 'Raw Ingredients'), ('packaged', 'Packaged Food'), ('beverages', 'Beverages'), ('bakery', 'Bakery Items'), ('other', 'Other')], default='other', max_length=50)),
                ('quantity', models.CharField(max_length=100)),
                ('serves', models.PositiveIntegerField(default=1)),
                ('pickup_location', models.TextField()),
                ('pickup_lat', models.FloatField(blank=True, null=True)),
                ('pickup_lng', models.FloatField(blank=True, null=True)),
                ('delivery_lat', models.FloatField(blank=True, null=True)),
                ('delivery_lng', models.FloatField(blank=True, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('requested', 'Requested'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(limit_choices_to={'role': 'donor'}, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(blank=True, limit_choices_to={'role': 'volunteer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('heading', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_location', to='donations.donation')),
                ('volunteer', models.OneToOneField(limit_choices_to={'role': 'volunteer'}, on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('delivery_address', models.TextField()),
                ('required_by', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='donations.donation')),
                ('ngo', models.ForeignKey(limit_choices_to={'role': 'ngo'}, on_delete=django.db.models.deletion.CASCADE, related_name='food_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('ngo', 'donation')},
            },
        ),
    ]
