# Generated by Django 4.2.29 on 2026-04-01 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('order_id', models.CharField(blank=True, max_length=255)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('donation_type', models.CharField(choices=[('food', 'Food Donation'), ('supplies', 'Supplies'), ('medicine', 'Medicine'), ('clothes', 'Clothes'), ('general', 'General Fund')], default='food', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('clothes', 'Clothes'), ('medicine', 'Medicine'), ('books', 'Books'), ('toys', 'Toys'), ('utensils', 'Utensils'), ('blankets', 'Blankets'), ('shoes', 'Shoes'), ('hygiene', 'Hygiene Products'), ('school_supplies', 'School Supplies'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], default='good', max_length=20)),
                ('categories', models.CharField(choices=[('primary', 'Primary Focus - Food'), ('secondary', 'Secondary - Clothing & Essentials'), ('health', 'Health & Medicine'), ('education', 'Education')], default='secondary', max_length=50)),
                ('pickup_location', models.TextField()),
                ('pickup_lat', models.FloatField(blank=True, null=True)),
                ('pickup_lng', models.FloatField(blank=True, null=True)),
                ('delivery_lat', models.FloatField(blank=True, null=True)),
                ('delivery_lng', models.FloatField(blank=True, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('requested', 'Requested'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_items', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(blank=True, limit_choices_to={'role': 'volunteer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_item_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
